### ISSUE TITLE
LoadBalancer Service Struck in Pending State

### ISSUE THREAD

**Issue by chilu49** [F5Networks/f5-ipam-controller#152]
Before you raise a new bug, please ensure you have visited the troubleshooting guide 
- [ ] Visited the [troubleshooting guide](https://github.com/F5Networks/f5-ipam-controller/blob/main/docs/faq/README.md)

#### Setup Details
 FIC Version : 0.1.9
 CIS Version : 2.15.0     
 FIC Build: f5networks/f5-ipam-controller:latest
 CIS Build: f5networks/k8s-bigip-ctlr:latest       
 BIGIP Version: Big IP x.x.x      
 AS3 Version: 3.x      
 Orchestration: K8S      
 Orchestration Version:             
 Additional Setup details: <Platform/CNI Plugins/ cluster nodes/ etc>

#### Description  
IPAM controller pod is crashing with below message
unable to establish connection to DB, database is locked

Also none of loadbalancer's are getting provisioned. They are struck in pending state and the f5-cis-ctlr logs show below "skipping service '{ servicename namespace}' as its not used by any CIS monitored resource  

#### Steps To Reproduce
1)
2)
3)

#### Expected Result 
successfully provisioned LB with an external IP from the range allocated IPAM

#### Actual Result  
Service struck in pending state

#### Diagnostic Information
```buildoutcfg
<Configuration files, error messages, logs>
Note: Sanitize the data. For example, be mindful of IPs, ports, application names and URLs
Note: The following F5 article outlines the information required when opening an issue.
https://support.f5.com/csp/article/K60974137
```  

#### Observations (if any)

**Comment by trinaths** [comment]
@chilu49 Is this issue still valid.

**Comment by chilu49** [comment]
Hi
This issue is now resolved.
This was due to incorrect permission on PVC/PV which was a NFS storage
underneath
Thanks.
