### ISSUE TITLE
Infoblox Integration Using Extensible Attributes

### ISSUE THREAD

**Issue by jmorello-mdsol** [F5Networks/f5-ipam-controller#164]
#### Title
Infoblox Integration Using Extensible Attributes

#### Description
It would be extremely useful for us if we could configure the F5 IPAM Controller to find available address pools in Infoblox by using Extensible Attribute matches on networks.

#### Solution Proposed
The F5 IPAM Controller could take a set of Key/Value pairs representing Infoblox Extensible Attributes that would be used to dynamically discover a collection of network objects. The next available IP in one of those networks could be assigned to a VS, TS, LB service F5 CIS CRD. The Infoblox WAPI supports these actions.

**Comment by mikeoleary** [comment]
@trinaths this is the same customer as this issue with CIS: https://github.com/F5Networks/k8s-bigip-ctlr/issues/3655

Could we get a status update on this IPAM feature request? Customer would be happy to chat with PM if desired.

**Comment by trinaths** [comment]
Not prioritised or supported.
